In [58]:
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import numpy as np
import pandas as pd
data=pd.read_csv('/content/train aa.csv')
data.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2  ...         20       756  2549     9     7         19   
1        136        3  ...        905      1988  2631    17     3          7   
2        145        5  ...       1263      1716  2603    11     2          9   
3        131        6  ...       1216      1786  2769    16     8         11   
4        141        2  ...       1208      1212  1411     8     2         15   

   three_g  touch_screen  wifi  price_range  
0        0             0     1            1  
1        1             1     0            2  
2        1             1     0            2  
3        1             0     0            2  
4        1             1     0            1  

[5 rows x 21 columns]

In [ ]:
y=data['price_range']
print(y)

0       1
1       2
2       2
3       2
4       1
       ..
1995    0
1996    2
1997    3
1998    0
1999    3
Name: price_range, Length: 2000, dtype: int64


In [ ]:
x=data.drop('price_range',axis=1)
print(x)

      battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  pc  px_height  px_width   ram  sc_h  sc_w  \
0       0

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler(feature_range=(0,1))
xtrainaa_norm=scaler.fit_transform(x)
print(xtrainaa_norm)

[[0.22778891 0.         0.68       ... 0.         0.         1.        ]
 [0.34736139 1.         0.         ... 1.         1.         0.        ]
 [0.04141617 1.         0.         ... 1.         1.         0.        ]
 ...
 [0.94188377 0.         0.16       ... 1.         1.         0.        ]
 [0.6753507  0.         0.16       ... 1.         1.         1.        ]
 [0.00601202 1.         0.6        ... 1.         1.         1.        ]]


In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(xtrainaa_norm,y,test_size=0.3)

In [ ]:
print(x_train)

[[0.22311289 0.         0.12       ... 1.         1.         1.        ]
 [0.72745491 0.         0.4        ... 1.         0.         0.        ]
 [0.3239813  1.         0.12       ... 1.         1.         0.        ]
 ...
 [0.96659987 0.         0.92       ... 0.         1.         0.        ]
 [0.70340681 1.         0.         ... 0.         0.         0.        ]
 [0.54175017 0.         0.32       ... 1.         1.         1.        ]]


In [ ]:
print(x_test)

[[0.98597194 0.         0.32       ... 0.         0.         0.        ]
 [0.24315297 0.         0.96       ... 0.         0.         1.        ]
 [0.39812959 0.         0.12       ... 1.         0.         1.        ]
 ...
 [0.23446894 0.         0.52       ... 1.         0.         0.        ]
 [0.96726787 0.         0.32       ... 1.         0.         0.        ]
 [0.999332   1.         0.52       ... 1.         0.         0.        ]]


In [ ]:
print(y_train)

1343    2
1176    3
1634    0
982     3
1520    3
       ..
776     0
884     2
471     3
496     3
807     3
Name: price_range, Length: 1400, dtype: int64


In [ ]:
print(y_test)

1008    3
1627    3
1158    2
1880    2
299     1
       ..
642     0
1754    2
1505    0
177     3
309     2
Name: price_range, Length: 600, dtype: int64


In [ ]:
import numpy as np
import pandas as pd
data=pd.read_csv('/content/heart.csv')
data.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [ ]:
y=data['target']
print(y)

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64


In [ ]:
import numpy as np
import pandas as pd
data=pd.read_csv('/content/heart.csv')
data.head()


age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [ ]:
y=data['target']
print(y)

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64


In [ ]:
x=data.drop('target',axis=1)
print(x)

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  
0        0   0     1  
1        0   0     2  
2        2   0    

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler(feature_range=(0,1))
xheart_norm=scaler.fit_transform(x)
print(xheart_norm)

[[0.70833333 1.         1.         ... 0.         0.         0.33333333]
 [0.16666667 1.         0.66666667 ... 0.         0.         0.66666667]
 [0.25       0.         0.33333333 ... 1.         0.         0.66666667]
 ...
 [0.8125     1.         0.         ... 0.5        0.5        1.        ]
 [0.58333333 1.         0.         ... 0.5        0.25       1.        ]
 [0.58333333 0.         0.33333333 ... 0.5        0.25       0.66666667]]


In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(xheart_norm,y,test_size=0.3)

In [ ]:
print(x_train)

[[0.66666667 1.         1.         ... 0.5        0.5        0.66666667]
 [0.1875     1.         1.         ... 0.5        0.         1.        ]
 [0.45833333 1.         0.66666667 ... 1.         0.         0.66666667]
 ...
 [0.6875     0.         0.         ... 0.5        0.         0.66666667]
 [0.77083333 0.         0.         ... 0.5        0.5        1.        ]
 [0.60416667 0.         0.         ... 0.5        0.5        0.33333333]]


In [ ]:
print(x_test)

[[0.52083333 1.         0.33333333 ... 1.         0.         1.        ]
 [0.58333333 0.         0.         ... 1.         0.25       0.66666667]
 [0.33333333 0.         0.         ... 0.5        0.         0.66666667]
 ...
 [0.5625     1.         0.         ... 0.5        0.25       0.66666667]
 [0.25       0.         0.33333333 ... 1.         0.         0.66666667]
 [0.25       1.         0.33333333 ... 1.         0.         0.66666667]]


In [ ]:
print(y_train)

271    0
259    0
27     1
6      1
164    1
      ..
162    1
270    0
96     1
260    0
292    0
Name: target, Length: 212, dtype: int64


In [ ]:
print(y_test)

61     1
59     1
107    1
112    1
127    1
      ..
209    0
276    0
214    0
134    1
133    1
Name: target, Length: 91, dtype: int64
